"""An RNA string is a string formed from the alphabet containing 'A', 'C', 'G', and 'U'.

Given a DNA string t corresponding to a coding strand, its transcribed RNA string u is formed by replacing all occurrences of 'T' in t with 'U' in u.

Given: A DNA string t having length at most 1000 nt.

Return: The transcribed RNA string of t."""

DNA_string_practice = "GATGGAACTTGACTACGTAAATT"

question = """GGTGCCACCCTAGTACACTGATTGTTTATACATGTGCCTGAGCGACTGTCTCTAACCAGAGGCCCTAGCCTGAACCAGCCGGGGCATTACGTATGTAGCTCTTAGGCCGGTACTTGACTCTTTACAGACCTCACTGGTACAACGTCGGACATGAAGAAGCATTTTCATGTCGGTGAATGCCACAACACTAGCGCGTCGTCTATTCATGGAAGGGTCCCCCCTACATTTATTGTGTGTATTAATCTTGCAAACCGTGATCGCTACCCACCACCTGAACAACCAGGTTACTAATTTGTATCCTTGGACTGATGAAAGAGGTTGATTCTACGGTGACCGTCATCTACGCACTCCCGCGCTGCGACGCTTTGGTAGTGATGGCGGTGCTGACTCTCTCCGAGTACCATTCGGCAGCTGAGGTACTGTCGTGACCTTAGTGTCATTGAGTTAACGCCGTGGGATTCTAGTGCAGTTATGCGGGCGTGTGTTTTTGAAAGTGGGACCCCTATTGTAGCCGGGTACCAAAACCAGCTGGGGATCCAACCATCGGTAAAAGCGGGTAATGTTGGCAGTCTCTCTTGTTTTCAACTAGTACCCTGAAGATCGATATGTCCGATAGGTGACCTTATATTTGATAGGGGCCGCCCATTATGGGATGTAATGCTACACGGCCAGCATCGTCAAAAACTTAAACAGTGGCGGGACTCATTACTCGTCCCGTAGGTTACTGAAGACACGAAATGGCCGAGAAGTGGGACGAAAGTTTGCGTAGTAAGACTACGGTTGTTCTTAAGAGGACTAACGTGAAGATTAGGGGGAAGTCCGACTCTTTGCTAGAGCCGACTATCTTTATTACTTACGATCCTTACAGGTGGCCTGAGTAGAGCATTACTCAGCGCCTATCTGTACTGCGCTACTGAGGTGGGTTCTGCTCTTTCCCACTCGCACACAGTGCAGGAGTT
"""


def transcribe(string):
    """function that replaces all T's with a U"""
    RNA = string.replace("T", "U")
    print(RNA)
    return RNA


transcribe(question)
